### ISSUE TITLE
Receiving new error that just states "Expected Load"

### ISSUE THREAD

**Issue by SkytheWitcher** [whidl/whidl#46]
Upon trying to test code using --top-level-file, I was instructed to use a new command that is simply --test-file. Upon using it, I received a new error I have not encountered that is not descriptive to be entirely honest

![whidlBugReport1](https://github.com/whidl/whidl/assets/122322513/914c2a34-9c44-40d6-8bc7-cdf10d4c96ae)

**Comment by defreez** [comment]
This is actually working as intended. The `test` command can only be used for the test files. You have passed an HDL file.

**Comment by SkytheWitcher** [comment]
Whoops, I meant to be using whidl check! Not test.
